language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - PYMYSQL_VERSION=0.6.6
  - PYMYSQL_VERSION=0.6.2

install:
  - pip install PyMySQL==$PYMYSQL_VERSION . pytest mock codecov

script:
  - coverage run --source mycli -m py.test

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
