language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install PyMySQL pytest mock codecov pexpect behave pytest-cov
  - pip install git+https://github.com/hayd/pep8radius.git
  - pip install -e .

script:
  - set -e
  - py.test --cov-report= --cov=mycli
  - behave test/features
  - ./setup.py lint
  - set +e

after_success:
  - coverage combine
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
